version: "3.8"

services:
  db:
    image: mysql:8.0.31
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - "./api/tmp/db:/var/lib/mysql"

  api:
    build:
      context: ./api
      args:
        WORKDIR: app
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      API_DOMAIN: "localhost:8080"
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - "./api:/app"
    depends_on:
      - db
    ports:
      - "3000:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: app
        API_URL: "http://localhost:3000"
    command: yarn run dev
    environment:
      API_KEY: $API_KEY
    volumes:
      - "./front:/app"
    ports:
      - "8080:3000"
    depends_on:
      - api
