version: "3.8"

services:
  db:
    image: mysql:8.0.31
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - "./api/tmp/db:/var/lib/mysql"

  api:
    build: ./api
    command: rails s -b 0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      API_DOMAIN: $API_DOMAIN
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - "./api:/app"
    depends_on:
      - db
    ports:
      - "3000:3000"

  front:
    build:
      context: ./front
      args:
        API_URL: $API_URL
    command: yarn run dev
    environment:
      API_KEY: $API_KEY
      NODE_ENV: $NODE_ENV
    volumes:
      - "./front:/app"
    ports:
      - "8080:3000"
    depends_on:
      - api
