version: "3.8"

services:
  db:
    image: mysql:8.0.31
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - "./api/tmp/db:/var/lib/mysql"

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - "./api:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    environment:
      API_KEY: $API_KEY
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api
