version: "3.8"

services:
  db:
    image: mysql:8.0.31
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - "./api/tmp/db:/var/lib/mysql"

  api:
    build: ./api
    command: bundle exec puma -C config/puma.rb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      FRONT_DOMAIN: $FRONT_DOMAIN
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - "./api:/app"
      - "public-data:/app/public"
      - "tmp-data:/app/tmp"
    ports: # なくても問題ないが一貫性を持たせるため明示的に定義
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build: ./api/nginx
    volumes:
      - "public-data:/app/public"
      - "tmp-data:/app/tmp"
    ports: # なくても問題ないが一貫性を持たせるため明示的に定義
      - "80:80"
    depends_on:
      - api

  front:
    build: ./front
    command: yarn dev
    environment:
      API_KEY: $API_KEY
      NODE_ENV: $NODE_ENV
    volumes:
      - "./front:/app"
    ports:
      - "8080:3000"
    depends_on:
      - nginx

volumes:
  public-data:
  tmp-data:
